"""add coding practice tables

Revision ID: d2834e8847a5
Revises: fb177b67f04f
Create Date: 2026-08-16 11:56:37.246379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2834e8847a5'
down_revision: Union[str, Sequence[str], None] = 'fb177b67f04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('category', sa.Enum('ARRAYS', 'STRINGS', 'HASHING', 'TWO_POINTERS', 'SLIDING_WINDOW', 'STACK', 'QUEUE', 'LINKED_LIST', 'TREES', 'BST', 'HEAP', 'GRAPHS', 'DFS', 'BFS', 'GREEDY', 'DYNAMIC_PROGRAMMING', 'BACKTRACKING', 'BIT_MANIPULATION', 'MATH', name='questioncategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_coding_questions_category'), 'coding_questions', ['category'], unique=False)
    op.create_index(op.f('ix_coding_questions_difficulty'), 'coding_questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_coding_questions_id'), 'coding_questions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_questions_slug'), 'coding_questions', ['slug'], unique=True)
    op.create_table('coding_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_tags_id'), 'coding_tags', ['id'], unique=False)
    op.create_index(op.f('ix_coding_tags_name'), 'coding_tags', ['name'], unique=True)
    op.create_table('coding_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['coding_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_examples_id'), 'coding_examples', ['id'], unique=False)
    op.create_index(op.f('ix_coding_examples_question_id'), 'coding_examples', ['question_id'], unique=False)
    op.create_table('coding_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('easy_solved', sa.Integer(), nullable=False),
    sa.Column('medium_solved', sa.Integer(), nullable=False),
    sa.Column('hard_solved', sa.Integer(), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=False),
    sa.Column('total_attempted', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('accepted_submissions', sa.Integer(), nullable=False),
    sa.Column('acceptance_rate', sa.Float(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_solved_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_coding_progress_user_id'), 'coding_progress', ['user_id'], unique=False)
    op.create_table('coding_question_tags',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['coding_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['coding_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    op.create_table('coding_starter_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', 'JAVA', 'C', 'CPP', name='programminglanguage'), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('reference_solution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['coding_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_starter_codes_id'), 'coding_starter_codes', ['id'], unique=False)
    op.create_index(op.f('ix_coding_starter_codes_language'), 'coding_starter_codes', ['language'], unique=False)
    op.create_index(op.f('ix_coding_starter_codes_question_id'), 'coding_starter_codes', ['question_id'], unique=False)
    op.create_table('coding_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', 'JAVA', 'C', 'CPP', name='programminglanguage'), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'WRONG_ANSWER', 'COMPILATION_ERROR', 'RUNTIME_ERROR', 'TIME_LIMIT_EXCEEDED', name='submissionstatus'), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('passed_test_cases', sa.Integer(), nullable=False),
    sa.Column('total_test_cases', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('compiler_output', sa.Text(), nullable=True),
    sa.Column('is_submission', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['coding_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_submissions_id'), 'coding_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_coding_submissions_language'), 'coding_submissions', ['language'], unique=False)
    op.create_index(op.f('ix_coding_submissions_question_id'), 'coding_submissions', ['question_id'], unique=False)
    op.create_index(op.f('ix_coding_submissions_status'), 'coding_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_coding_submissions_user_id'), 'coding_submissions', ['user_id'], unique=False)
    op.create_table('coding_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['coding_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_test_cases_id'), 'coding_test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_coding_test_cases_question_id'), 'coding_test_cases', ['question_id'], unique=False)
    op.drop_index(op.f('ix_job_matches_id'), table_name='job_matches')
    op.drop_table('job_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('matching_skills', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('missing_skills', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weaknesses', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('suggestions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('job_matches_resume_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_matches_pkey'))
    )
    op.create_index(op.f('ix_job_matches_id'), 'job_matches', ['id'], unique=False)
    op.drop_index(op.f('ix_coding_test_cases_question_id'), table_name='coding_test_cases')
    op.drop_index(op.f('ix_coding_test_cases_id'), table_name='coding_test_cases')
    op.drop_table('coding_test_cases')
    op.drop_index(op.f('ix_coding_submissions_user_id'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_status'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_question_id'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_language'), table_name='coding_submissions')
    op.drop_index(op.f('ix_coding_submissions_id'), table_name='coding_submissions')
    op.drop_table('coding_submissions')
    op.drop_index(op.f('ix_coding_starter_codes_question_id'), table_name='coding_starter_codes')
    op.drop_index(op.f('ix_coding_starter_codes_language'), table_name='coding_starter_codes')
    op.drop_index(op.f('ix_coding_starter_codes_id'), table_name='coding_starter_codes')
    op.drop_table('coding_starter_codes')
    op.drop_table('coding_question_tags')
    op.drop_index(op.f('ix_coding_progress_user_id'), table_name='coding_progress')
    op.drop_table('coding_progress')
    op.drop_index(op.f('ix_coding_examples_question_id'), table_name='coding_examples')
    op.drop_index(op.f('ix_coding_examples_id'), table_name='coding_examples')
    op.drop_table('coding_examples')
    op.drop_index(op.f('ix_coding_tags_name'), table_name='coding_tags')
    op.drop_index(op.f('ix_coding_tags_id'), table_name='coding_tags')
    op.drop_table('coding_tags')
    op.drop_index(op.f('ix_coding_questions_slug'), table_name='coding_questions')
    op.drop_index(op.f('ix_coding_questions_id'), table_name='coding_questions')
    op.drop_index(op.f('ix_coding_questions_difficulty'), table_name='coding_questions')
    op.drop_index(op.f('ix_coding_questions_category'), table_name='coding_questions')
    op.drop_table('coding_questions')
    # ### end Alembic commands ###
